POST https://node-from-zero-9gx2.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###   //Separa as requisições

GET https://node-from-zero-9gx2.onrender.com/videos

###

PUT https://node-from-zero-9gx2.onrender.com/videos/b79bac64-aa18-49d9-8ceb-de582271a99c
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo vídeo agora",
    "duration": 180
}

### 

DELETE https://node-from-zero-9gx2.onrender.com/videos/b79bac64-aa18-49d9-8ceb-de582271a99c
